# Generated by Django 4.2.1 on 2023-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_email_address_validated_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_address_validated",
            field=models.BooleanField(default=False),
        ),
    ]
