# Generated by Django 4.2.1 on 2023-06-11 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_id", models.CharField(max_length=50, unique=True)),
                ("account_type", models.CharField(max_length=50, null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "BankAccount",
                "verbose_name_plural": "BankAccounts",
            },
        ),
    ]
