# Generated by Django 4.2.1 on 2023-07-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recurring_expenses", "0002_rename_fee_recurringexpense_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringexpense",
            name="particulars",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
