# Generated by Django 4.2.1 on 2023-06-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('user_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=50)),
                ('memo', models.CharField(blank=True, max_length=50, null=True)),
                ('sic', models.CharField(blank=True, max_length=50, null=True)),
                ('mcc', models.CharField(blank=True, max_length=50, null=True)),
                ('checknum', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
