# Generated by Django 4.2.1 on 2023-06-11 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=50, unique=True)),
                ("transaction_type", models.CharField(max_length=50)),
                ("payee", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("user_date", models.DateTimeField(null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("memo", models.CharField(blank=True, max_length=50, null=True)),
                ("sic", models.CharField(blank=True, max_length=50, null=True)),
                ("mcc", models.CharField(blank=True, max_length=50, null=True)),
                ("checknum", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.bankaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
