# Generated by Django 4.2.1 on 2023-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="user_date",
            field=models.DateTimeField(null=True),
        ),
    ]
